### ISSUE TITLE
Missing Package ggbiplot

### ISSUE THREAD

**Issue by tu-yujie** [jtr13/cc22spring#55]
It seems that we are still missing a package "ggbiplot"

**Comment by jtr13** [comment]
You can add it directly to this file: https://github.com/jtr13/cc22spring/blob/main/DESCRIPTION -- keep the packages in alphabetical order so it's easier to see if a package is listed or not.

**Comment by tu-yujie** [comment]
I have added the package ("vqv/ggbiplot") to the file: https://github.com/jtr13/cc22spring/blob/main/DESCRIPTION
But it still says "there is no package called 'ggbiplot'"

**Comment by jtr13** [comment]
It looks like it was removed, not sure why. Can you try adding it again?

**Comment by tu-yujie** [comment]
I can still see the modification here. Did I do something wrong?
![CleanShot 2022-04-02 at 11 43 31@2x](https://user-images.githubusercontent.com/65487415/161390676-24bcfbef-98c9-4415-8979-8c5c3c28c389.png)

**Comment by jtr13** [comment]
Ah, if it's installed from GitHub it needs to be listed _both_ in Imports and Remotes -- the latter just specifies where to look for it.

**Comment by tu-yujie** [comment]
Ok I see. I have added ggbiplot under both imports and remotes and it works now!

**Comment by jtr13** [comment]
Ok great!
