### ISSUE TITLE
html_denpendcy problem

### ISSUE THREAD

**Issue by tu-yujie** [jtr13/cc22spring#61]
@jtr13  It seems that my [ggmap_ggplot_tmap_maps.Rmd](https://github.com/jtr13/cc22spring/blob/main/ggmap_ggplot_tmap_maps.Rmd) file failed to complie due to a html_denpendcy problem.
`path for html_dependency not found:  #/tmp/RtmpCyiB5n`

 I believe the code that causes this problem is `tmap_mode("view)`. I have found similar issue [here](https://github.com/rstudio/bookdown/issues/15) but not so sure what should I do to solve it.

I got the same issue when compiling it locally: I was able to knit it with `cache=TRUE` for the first time and will get a similar compile error when knitting it for the second time. And the solution was to delete the cache and it will be able to compile again. But I tried to delete `cache=TRUE` on the main branch but it still gets the same error.

**Comment by jtr13** [comment]
Good sleuthing. Honestly I'm surprised that it works at all with `.Rmd` -- I thought `tmap_mode("view")` can only be run in the Console. I think we should just comment out the lines and add a line `# not run`.

**Comment by tu-yujie** [comment]
I see. Thank you!
