### ISSUE TITLE
Failed to build source package 'placeholder'

### ISSUE THREAD

**Issue by tu-yujie** [jtr13/cc22spring#62]
After adding [timeseriesanalysis.Rmd](https://github.com/jtr13/cc22spring/blob/main/timeseriesanalysis.Rmd), it fails to compile due to error `<callr_remote_error: Failed to build source package 'placeholder'>`. Not so sure what to do here. @jtr13

**Comment by jtr13** [comment]
Can you add `placeholder` to the `DESCRIPTION` file? Not sure if that will help but worth a try.
