### ISSUE TITLE
possible package name conflict

### ISSUE THREAD

**Issue by tu-yujie** [jtr13/cc22spring#64]
@jtr13 It seems that there is a package called `recharts` in this [file](https://github.com/jtr13/cc22spring/pull/28/files#diff-ba5a7068414e7dc1c4fd03f655fee9e80d87a6611f1af954890f5ddd83c977e7) have the same name in `DESCRIPTION` but comes from different source: `# install_github('recharts', 'taiyun')` vs `madlogos/recharts`

**Comment by jtr13** [comment]
Oh, that's confusing. Let's try changing `madlogos` to `tiayun` and see what happens.

**Comment by jtr13** [comment]
Actually it works with `taiyun`—there was a different problem which I (temporarily) fixed. It’s working now.
